services:
  db:
    image: postgres:17
    container_name: clinic_finances_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_finances
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
