"""add procedures table and FK from insurance_claims

Revision ID: 014ddd4166b2
Revises: 6cd71b06164f
Create Date: 2026-02-16 21:02:40.828406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014ddd4166b2'
down_revision: Union[str, Sequence[str], None] = '6cd71b06164f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('cd_procedure', sa.String(length=30), nullable=False, comment='Código identificador único do procedimento (código TUSS)'),
    sa.Column('nm_procedure', sa.String(length=200), nullable=False, comment='Nome do procedimento'),
    sa.Column('vl_procedure', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor do procedimento (preço de tabela)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização do registro'),
    sa.PrimaryKeyConstraint('cd_procedure'),
    comment='Cadastro de procedimentos realizados na clínica'
    )
    op.create_index(op.f('ix_procedures_nm_procedure'), 'procedures', ['nm_procedure'], unique=False)
    op.alter_column('insurance_claims', 'cd_procedure',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_comment='Código do procedimento realizado',
               existing_nullable=False)
    # Populate procedures from existing insurance_claims data (vl_procedure = 0 as placeholder)
    op.execute(
        """
        INSERT INTO procedures (cd_procedure, nm_procedure, vl_procedure)
        SELECT DISTINCT cd_procedure, nm_procedure, 0
        FROM insurance_claims
        ON CONFLICT DO NOTHING
        """
    )
    op.create_foreign_key('fk_insurance_claims_cd_procedure', 'insurance_claims', 'procedures', ['cd_procedure'], ['cd_procedure'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_insurance_claims_cd_procedure', 'insurance_claims', type_='foreignkey')
    op.alter_column('insurance_claims', 'cd_procedure',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_comment='Código do procedimento realizado',
               existing_nullable=False)
    op.drop_index(op.f('ix_procedures_nm_procedure'), table_name='procedures')
    op.drop_table('procedures')
    # ### end Alembic commands ###
