"""add invoice table

Revision ID: 34c075198a77
Revises: 014ddd4166b2
Create Date: 2026-03-01 17:29:31.389651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c075198a77'
down_revision: Union[str, Sequence[str], None] = '014ddd4166b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id_invoice', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID único criado automaticamente para cada fatura'),
    sa.Column('dt_service', sa.Date(), nullable=False, comment='Data de realização do atendimento'),
    sa.Column('cd_patient', sa.String(length=30), nullable=False, comment='Código do paciente (código do beneficiário)'),
    sa.Column('cd_procedure', sa.String(length=30), nullable=False, comment='Código identificador único do procedimento (código TUSS)'),
    sa.Column('qt_procedure', sa.Integer(), nullable=False, comment='Quantidade do procedimento realizado'),
    sa.Column('vl_procedure', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor total faturado do procedimento'),
    sa.Column('nr_page', sa.Integer(), nullable=False, comment='Página em que o registro é encontrado no relatório original'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano de referencia'),
    sa.Column('nm_file', sa.String(length=30), nullable=False, comment='Nome do arquivo de origem'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização do registro'),
    sa.ForeignKeyConstraint(['cd_patient'], ['patients.cd_patient'], ),
    sa.ForeignKeyConstraint(['cd_procedure'], ['procedures.cd_procedure'], ),
    sa.PrimaryKeyConstraint('id_invoice'),
    comment='Faturas importadas da operadora São Lucas'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
