"""remove id from patients, add table and column comments

Revision ID: 654cec6385ab
Revises: 5898701e0bbe
Create Date: 2026-02-14 18:13:49.764079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '654cec6385ab'
down_revision: Union[str, Sequence[str], None] = '5898701e0bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único do registro de log',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('logs', 'level',
               existing_type=sa.VARCHAR(length=20),
               comment='Nível de severidade do log (DEBUG, INFO, WARNING, ERROR, CRITICAL)',
               existing_nullable=False)
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               comment='Mensagem descritiva do evento registrado',
               existing_nullable=False)
    op.alter_column('logs', 'module',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome do módulo Python que originou o log',
               existing_nullable=True)
    op.alter_column('logs', 'function',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome da função que originou o log',
               existing_nullable=True)
    op.alter_column('logs', 'line',
               existing_type=sa.INTEGER(),
               comment='Número da linha no código fonte que originou o log',
               existing_nullable=True)
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data e hora em que o log foi registrado',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'logs',
        'Registro de logs da aplicação capturados pelo Loguru',
        existing_comment=None,
        schema=None
    )
    op.alter_column('patients', 'cd_patient',
               existing_type=sa.VARCHAR(length=30),
               comment='Código identificador único do paciente (código do beneficiário)',
               existing_nullable=False)
    op.alter_column('patients', 'nm_patient',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome completo do paciente',
               existing_nullable=False)
    op.alter_column('patients', 'ds_address',
               existing_type=sa.VARCHAR(length=300),
               comment='Endereço residencial do paciente',
               existing_nullable=False)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data e hora de criação do registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patients_cd_patient'), table_name='patients')
    op.drop_constraint('patients_pkey', 'patients', type_='primary')
    op.drop_column('patients', 'id')
    op.create_primary_key('patients_pkey', 'patients', ['cd_patient'])
    op.create_table_comment(
        'patients',
        'Cadastro de pacientes atendidos na clínica',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patients_pkey', 'patients', type_='primary')
    op.add_column('patients', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_primary_key('patients_pkey', 'patients', ['id'])
    op.drop_table_comment(
        'patients',
        existing_comment='Cadastro de pacientes atendidos na clínica',
        schema=None
    )
    op.create_index(op.f('ix_patients_cd_patient'), 'patients', ['cd_patient'], unique=True)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data e hora de criação do registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'ds_address',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Endereço residencial do paciente',
               existing_nullable=False)
    op.alter_column('patients', 'nm_patient',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome completo do paciente',
               existing_nullable=False)
    op.alter_column('patients', 'cd_patient',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Código identificador único do paciente (código do beneficiário)',
               existing_nullable=False)
    op.drop_table_comment(
        'logs',
        existing_comment='Registro de logs da aplicação capturados pelo Loguru',
        schema=None
    )
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data e hora em que o log foi registrado',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('logs', 'line',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número da linha no código fonte que originou o log',
               existing_nullable=True)
    op.alter_column('logs', 'function',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome da função que originou o log',
               existing_nullable=True)
    op.alter_column('logs', 'module',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome do módulo Python que originou o log',
               existing_nullable=True)
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mensagem descritiva do evento registrado',
               existing_nullable=False)
    op.alter_column('logs', 'level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Nível de severidade do log (DEBUG, INFO, WARNING, ERROR, CRITICAL)',
               existing_nullable=False)
    op.alter_column('logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único do registro de log',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
