"""create table tb_recibos_sao_lucas at silver schema

Revision ID: 855fd9e3cb15
Revises: 8d5de2a149f6
Create Date: 2026-03-08 17:19:34.708905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855fd9e3cb15'
down_revision: Union[str, Sequence[str], None] = '8d5de2a149f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_recibos_sao_lucas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único do registro (UUID)'),
    sa.Column('dt_atendimento', sa.Date(), nullable=False, comment='Data de realização do atendimento'),
    sa.Column('cd_beneficiario', sa.String(length=18), nullable=False, comment='Código do beneficiário (código do paciente)'),
    sa.Column('cd_procedimento', sa.String(length=8), nullable=False, comment='Código do procedimento realizado'),
    sa.Column('qt_procedimento', sa.Integer(), nullable=False, comment='Quantidade do procedimento realizado'),
    sa.Column('vl_procedimento', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Valor do procedimento realizado'),
    sa.Column('nr_pagina', sa.Integer(), nullable=False, comment='Número da página do relatório de atendimento onde o procedimento está descrito'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano base do arquivo no formato YYYYMM (ex: 202401)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nome do arquivo de origem do registro'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data e hora de última atualização do registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_recibos_sao_lucas')),
    schema='slv',
    comment='Tabela de recibos importados da operadora São Lucas, na camada silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_recibos_sao_lucas', schema='slv')
    # ### end Alembic commands ###
