"""create table tb_recibos_sao_lucas at bronze schema

Revision ID: 8d5de2a149f6
Revises: 32cb5094e56e
Create Date: 2026-03-08 16:55:26.485579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5de2a149f6'
down_revision: Union[str, Sequence[str], None] = '32cb5094e56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_recibos_sao_lucas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único do registro (UUID)'),
    sa.Column('dt_atendimento', sa.String(length=10), nullable=False, comment='Data de realização do atendimento (formato: dd/mm/yyyy)'),
    sa.Column('cd_beneficiario', sa.String(length=18), nullable=False, comment='Código do beneficiário (código do paciente)'),
    sa.Column('cd_procedimento', sa.String(length=8), nullable=False, comment='Código do procedimento realizado'),
    sa.Column('qt_procedimento', sa.String(length=3), nullable=False, comment='Quantidade do procedimento realizado'),
    sa.Column('vl_procedimento', sa.String(length=10), nullable=False, comment='Valor do procedimento realizado'),
    sa.Column('nr_pagina', sa.String(length=3), nullable=False, comment='Número da página do relatório de atendimento onde o procedimento está descrito'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano base do arquivo no formato YYYYMM (ex: 202401)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nome do arquivo de origem do recibo'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data e hora de última atualização do registro'),
    sa.Column('silver_exported', sa.Boolean(), nullable=False, comment='Flag indicando se o registro foi exportado para a camada silver'),
    sa.Column('silver_date_export', sa.DateTime(), nullable=True, comment='Data e hora de exportação para a camada silver'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_recibos_sao_lucas')),
    schema='brz',
    comment='Tabela de recibos importados da operadora São Lucas, na camada bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_recibos_sao_lucas', schema='brz')
    # ### end Alembic commands ###
