"""create insurance_claims table

Revision ID: ab09b1768619
Revises: 654cec6385ab
Create Date: 2026-02-15 15:23:36.957149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab09b1768619'
down_revision: Union[str, Sequence[str], None] = '654cec6385ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_claims',
    sa.Column('nr_claim', sa.String(length=8), nullable=False, comment='Número do atendimento (guia)'),
    sa.Column('nr_request', sa.String(length=8), nullable=False, comment='Número da solicitação'),
    sa.Column('cd_patient', sa.String(length=30), nullable=False, comment='Código do paciente (código do beneficiário)'),
    sa.Column('dt_issue', sa.Date(), nullable=False, comment='Data de emissão do atendimento'),
    sa.Column('dm_service', sa.DateTime(), nullable=False, comment='Data e hora de realização do atendimento'),
    sa.Column('st_claim', sa.String(length=20), nullable=False, comment='Status do atendimento (ex: Autorizada, Pendente)'),
    sa.Column('tp_claim', sa.String(length=20), nullable=False, comment='Tipo do atendimento (ex: Consulta, Senha)'),
    sa.Column('fg_return', sa.Boolean(), nullable=False, comment='Flag indicando se o atendimento é retorno'),
    sa.Column('cd_procedure', sa.String(length=20), nullable=False, comment='Código do procedimento realizado'),
    sa.Column('nm_procedure', sa.String(length=200), nullable=False, comment='Nome do procedimento realizado'),
    sa.Column('qt_procedure', sa.Integer(), nullable=False, comment='Quantidade do procedimento realizado'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização do registro'),
    sa.ForeignKeyConstraint(['cd_patient'], ['patients.cd_patient'], ),
    sa.PrimaryKeyConstraint('nr_claim'),
    comment='Atendimentos realizados no período, importados da operadora São Lucas'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_claims')
    # ### end Alembic commands ###
