"""create table atentimentos sao lucas silver

Revision ID: acb95ea1ed3d
Revises: c45701abe82a
Create Date: 2026-03-08 14:57:26.652793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb95ea1ed3d'
down_revision: Union[str, Sequence[str], None] = 'c45701abe82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_solicitacoes_sao_lucas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único do registro (UUID)'),
    sa.Column('nr_solicitacao', sa.Integer(), nullable=False, comment='Número da solicitação.'),
    sa.Column('dt_solicitacao', sa.DateTime(), nullable=False, comment='Data da abertura da solicitação'),
    sa.Column('dt_validade_solicitacao', sa.Date(), nullable=False, comment='Data do vencimento da solicitação'),
    sa.Column('cd_solicitante', sa.String(length=5), nullable=False, comment='Código do profissinal de saúde solicitante'),
    sa.Column('cd_operador', sa.String(length=255), nullable=False, comment='Código do usuário que registrou a solicitação no sistema'),
    sa.Column('nm_terminal', sa.String(length=255), nullable=True, comment='Nome do usuário master do sistema para identificação de onde partiu a solicitação'),
    sa.Column('nm_solicitante', sa.String(length=255), nullable=False, comment='Nome do profissional de saúde solicitante'),
    sa.Column('cd_beneficiario', sa.String(length=18), nullable=False, comment='Código do beneficiário (código do paciente)'),
    sa.Column('nm_beneficiario', sa.String(length=255), nullable=True, comment='Nome do beneficiário (nome do paciente)'),
    sa.Column('ds_especialidade', sa.String(length=255), nullable=False, comment='Especialidade do profissional de saúde solicitante'),
    sa.Column('cd_procedimento', sa.String(length=8), nullable=False, comment='Código do procedimento solicitado'),
    sa.Column('nm_procedimento', sa.String(length=255), nullable=False, comment='Nome do procedimento solicitado'),
    sa.Column('qt_solicitado', sa.Integer(), nullable=False, comment='Quantidade do procedimento solicitado'),
    sa.Column('qt_liberado', sa.Integer(), nullable=False, comment='Quantidade do procedimento solicitado que foi liberado pela operadora'),
    sa.Column('qt_executado', sa.Integer(), nullable=False, comment='Quantidade do procedimento solicitado que foi executado'),
    sa.Column('cd_prestador', sa.String(length=255), nullable=True, comment='Código do prestador (código do profissional ou instituição que realizou o procedimento)'),
    sa.Column('ds_especialidade_prestador', sa.String(length=255), nullable=True, comment='Especialidade do prestador que executou o procedimento solicitado'),
    sa.Column('st_solicitacao', sa.String(length=50), nullable=False, comment='Descrição do status da solicitação'),
    sa.Column('ds_especificacao', sa.String(length=255), nullable=True, comment='Descrições de especificações e orientações relacionadas ao procedimento solicitado, se disponíveis'),
    sa.Column('tp_solicitacao', sa.String(length=255), nullable=False, comment='Tipo de solicitação (ex: Consulta, Exame)'),
    sa.Column('cd_operador_cancelamento', sa.String(length=255), nullable=True, comment='Código do operador que cancelou a solicitação, se aplicável'),
    sa.Column('ds_observacao', sa.String(length=255), nullable=True, comment='Observações sobre a solicitação'),
    sa.Column('cd_auditor', sa.String(length=255), nullable=True, comment='Código do usuário que realizou a auditoria da solicitação, se disponível'),
    sa.Column('dt_agendamento', sa.Date(), nullable=True, comment='Data de agendamento para a realização do procedimento solicitado, se disponível'),
    sa.Column('cd_operador_agendamento', sa.String(length=255), nullable=True, comment='Código do operador que realizou o agendamento, se disponível'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano base do arquivo no formato YYYYMM (ex: 202401)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nome do arquivo de origem do atendimento'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data e hora de última atualização do registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_solicitacoes_sao_lucas')),
    schema='slv',
    comment='Tabela de solicitações importadas da operadora São Lucas, na camada silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_solicitacoes_sao_lucas', schema='slv')
    # ### end Alembic commands ###
