"""change column beneficiario to nullable

Revision ID: b06bac82c554
Revises: ba626ad5f0f7
Create Date: 2026-03-07 17:00:40.850493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06bac82c554'
down_revision: Union[str, Sequence[str], None] = 'ba626ad5f0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_atendimentos_sao_lucas', 'beneficiario',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Nome do beneficiário (nome do paciente)',
               schema='brz')
    op.alter_column('tb_atendimentos_sao_lucas', 'nm_beneficiario',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Nome do beneficiário (nome do paciente)',
               schema='slv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_atendimentos_sao_lucas', 'nm_beneficiario',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Nome do beneficiário (nome do paciente)',
               schema='slv')
    op.alter_column('tb_atendimentos_sao_lucas', 'beneficiario',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Nome do beneficiário (nome do paciente)',
               schema='brz')
    # ### end Alembic commands ###
