"""rename procedimento to procedimento_1 and add procedimento column

Revision ID: b1f9f88d502a
Revises: f7c4d50e21a4
Create Date: 2026-03-07 19:54:44.705876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f9f88d502a'
down_revision: Union[str, Sequence[str], None] = 'f7c4d50e21a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_solicitacoes_sao_lucas', sa.Column('procedimento_1', sa.String(length=255), nullable=False, comment='Nome do procedimento solicitado'), schema='brz')
    op.alter_column('tb_solicitacoes_sao_lucas', 'procedimento',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=8),
               comment='Código do procedimento solicitado',
               existing_comment='Nome do procedimento solicitado',
               existing_nullable=False,
               schema='brz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_solicitacoes_sao_lucas', 'procedimento',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=255),
               comment='Nome do procedimento solicitado',
               existing_comment='Código do procedimento solicitado',
               existing_nullable=False,
               schema='brz')
    op.drop_column('tb_solicitacoes_sao_lucas', 'procedimento_1', schema='brz')
    # ### end Alembic commands ###
