"""alter table terminal column to nullable true

Revision ID: c45701abe82a
Revises: c3e8a21f9b47
Create Date: 2026-03-07 20:12:04.228385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45701abe82a'
down_revision: Union[str, Sequence[str], None] = 'c3e8a21f9b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_solicitacoes_sao_lucas', 'terminal',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Nome do usuário master do sistema para identificação de onde partiu a solicitação',
               schema='brz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_solicitacoes_sao_lucas', 'terminal',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Nome do usuário master do sistema para identificação de onde partiu a solicitação',
               schema='brz')
    # ### end Alembic commands ###
