"""create bronze and silver tables

Revision ID: ca3ac103e0f9
Revises: 
Create Date: 2026-03-07 14:19:33.011268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3ac103e0f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_atendimentos_sao_lucas',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único do registro (UUID)'),
    sa.Column('terminal', sa.String(length=4), nullable=False, comment='Terminal de atendimento (ex: 0001, 0002)'),
    sa.Column('guia', sa.String(length=8), nullable=False, comment='Número do atendimento (guia)'),
    sa.Column('emissao', sa.String(length=10), nullable=False, comment='Data de emissão da guia (formato: dd/mm/yyyy)'),
    sa.Column('atendimento', sa.String(length=10), nullable=False, comment='Data de realização do atendimento (formato: dd/mm/yyyy)'),
    sa.Column('horario', sa.String(length=8), nullable=False, comment='Horário de realização do atendimento (formato: hh:mm:ss)'),
    sa.Column('emissao_tiss', sa.String(length=10), nullable=False, comment='Data de emissão da guia no formato TISS (formato: d/mm/yyyy)'),
    sa.Column('cd_beneficiario', sa.String(length=18), nullable=False, comment='Código do beneficiário (código do paciente)'),
    sa.Column('beneficiario', sa.String(length=255), nullable=False, comment='Nome do beneficiário (nome do paciente)'),
    sa.Column('endereco_beneficiario', sa.String(length=255), nullable=True, comment='Endereço do beneficiário (endereço do paciente)'),
    sa.Column('solicitante', sa.String(length=6), nullable=False, comment='Código do solicitante (código do profissional de saúde que solicitou o atendimento)'),
    sa.Column('solicitante_1', sa.String(length=255), nullable=False, comment='Nome do solicitante (nome do profissional de saúde que solicitou o atendimento)'),
    sa.Column('especialidade', sa.String(length=255), nullable=False, comment='Especialidade do atendimento (ex: Dermatologia, Pediatria)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status do atendimento (ex: AUTORIZADA, Pendente)'),
    sa.Column('tipo', sa.String(length=50), nullable=False, comment='Tipo do atendimento (ex: Consulta, Senha)'),
    sa.Column('retorno', sa.String(length=5), nullable=False, comment='Flag indicando se o atendimento é retorno (ex: Sim, Não)'),
    sa.Column('senha_terapia', sa.String(length=20), nullable=True, comment='Número da senha de terapia, se aplicável'),
    sa.Column('procedimento', sa.String(length=8), nullable=False, comment='Código do procedimento realizado'),
    sa.Column('procedimento_1', sa.String(length=255), nullable=False, comment='Nome do procedimento realizado'),
    sa.Column('quantidade', sa.String(length=10), nullable=False, comment='Quantidade do procedimento realizado'),
    sa.Column('sessoes_executadas', sa.String(length=10), nullable=True, comment='Número de sessões executadas, se aplicável'),
    sa.Column('prestador', sa.String(length=6), nullable=False, comment='Código do prestador (código do profissional de saúde que realizou o atendimento)'),
    sa.Column('prestador_1', sa.String(length=255), nullable=False, comment='Nome do prestador (nome do profissional de saúde que realizou o atendimento)'),
    sa.Column('especialidade_1', sa.String(length=255), nullable=False, comment='Especialidade do prestador (ex: Dermatologia, Pediatria)'),
    sa.Column('indicacao_clinica', sa.String(length=255), nullable=True, comment='Indicação clínica para o atendimento, se disponível'),
    sa.Column('status_export', sa.String(length=5), nullable=False, comment='Indica se o atendimento foi exportado no sistema de origem'),
    sa.Column('dt_export', sa.String(length=10), nullable=False, comment='Data de exportação do atendimento no sistema de origem (formato: dd/mm/yyyy)'),
    sa.Column('dt_senha', sa.String(length=10), nullable=False, comment='Data de geração da senha, se aplicável (formato: dd/mm/yyyy)'),
    sa.Column('operador_execucao', sa.String(length=6), nullable=False, comment='Código do operador que executou o atendimento, se disponível'),
    sa.Column('operador_senha', sa.String(length=6), nullable=True, comment='Código do operador que gerou a senha, se aplicável'),
    sa.Column('operador_canc', sa.String(length=6), nullable=True, comment='Código do operador que cancelou o atendimento, se aplicável'),
    sa.Column('observacao', sa.String(length=255), nullable=True, comment='Observações adicionais sobre o atendimento, se disponíveis'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano base do arquivo no formato YYYYMM (ex: 202401)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nome do arquivo de origem do atendimento'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data e hora de última atualização do registro'),
    sa.Column('silver_exported', sa.Boolean(), nullable=False, comment='Flag indicando se o registro foi exportado para a camada silver'),
    sa.Column('silver_date_export', sa.DateTime(), nullable=True, comment='Data e hora de exportação para a camada silver'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_atendimentos_sao_lucas')),
    schema='brz',
    comment='Tabela de atendimentos importados da operadora São Lucas, na camada bronze'
    )
    op.create_table('tb_atendimentos_sao_lucas',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único do registro (UUID)'),
    sa.Column('cd_terminal', sa.String(length=4), nullable=False, comment='Terminal de atendimento (ex: 0001, 0002)'),
    sa.Column('nr_guia', sa.Integer(), nullable=False, comment='Número do atendimento (guia)'),
    sa.Column('dt_emissao', sa.Date(), nullable=False, comment='Data de emissão da guia (formato: dd/mm/yyyy)'),
    sa.Column('dt_atendimento', sa.Date(), nullable=False, comment='Data de realização do atendimento (formato: dd/mm/yyyy)'),
    sa.Column('hr_atendimento', sa.Time(), nullable=False, comment='Horário de realização do atendimento (formato: hh:mm:ss)'),
    sa.Column('dt_emissao_tiss', sa.Date(), nullable=False, comment='Data de emissão da guia no formato TISS (formato: d/mm/yyyy)'),
    sa.Column('cd_beneficiario', sa.String(length=18), nullable=False, comment='Código do beneficiário (código do paciente)'),
    sa.Column('nm_beneficiario', sa.String(length=255), nullable=False, comment='Nome do beneficiário (nome do paciente)'),
    sa.Column('ds_endereco_beneficiario', sa.String(length=255), nullable=True, comment='Endereço do beneficiário (endereço do paciente)'),
    sa.Column('cd_solicitante', sa.String(length=6), nullable=False, comment='Código do solicitante (código do profissional de saúde que solicitou o atendimento)'),
    sa.Column('nm_solicitante', sa.String(length=255), nullable=False, comment='Nome do solicitante (nome do profissional de saúde que solicitou o atendimento)'),
    sa.Column('ds_especialidade', sa.String(length=255), nullable=False, comment='Especialidade do atendimento (ex: Dermatologia, Pediatria)'),
    sa.Column('st_atendimento', sa.String(length=50), nullable=False, comment='Status do atendimento (ex: AUTORIZADA, Pendente)'),
    sa.Column('tp_atendimento', sa.String(length=50), nullable=False, comment='Tipo do atendimento (ex: Consulta, Senha)'),
    sa.Column('fg_retorno', sa.Boolean(), nullable=False, comment='Flag indicando se o atendimento é retorno'),
    sa.Column('cd_senha_terapia', sa.String(length=20), nullable=True, comment='Número da senha de terapia, se aplicável'),
    sa.Column('cd_procedimento', sa.String(length=8), nullable=False, comment='Código do procedimento realizado'),
    sa.Column('ds_procedimento', sa.String(length=255), nullable=False, comment='Nome do procedimento realizado'),
    sa.Column('qt_procedimento', sa.Integer(), nullable=False, comment='Quantidade do procedimento realizado'),
    sa.Column('qt_sessoes_executadas', sa.Integer(), nullable=False, comment='Número de sessões executadas, se aplicável'),
    sa.Column('cd_prestador', sa.String(length=6), nullable=False, comment='Código do prestador (código do profissional de saúde que realizou o atendimento)'),
    sa.Column('nm_prestador', sa.String(length=255), nullable=False, comment='Nome do prestador (nome do profissional de saúde que realizou o atendimento)'),
    sa.Column('ds_especialidade_prestador', sa.String(length=255), nullable=False, comment='Especialidade do prestador (ex: Dermatologia, Pediatria)'),
    sa.Column('ds_indicacao_clinica', sa.String(length=255), nullable=True, comment='Indicação clínica para o atendimento, se disponível'),
    sa.Column('st_export', sa.String(length=5), nullable=False, comment='Indica se o atendimento foi exportado no sistema de origem'),
    sa.Column('dt_export', sa.Date(), nullable=False, comment='Data de exportação do atendimento no sistema de origem (formato: dd/mm/yyyy)'),
    sa.Column('dt_senha', sa.String(length=10), nullable=False, comment='Data de geração da senha, se aplicável (formato: dd/mm/yyyy)'),
    sa.Column('cd_operador_execucao', sa.String(length=6), nullable=False, comment='Código do operador que executou o atendimento, se disponível'),
    sa.Column('cd_operador_senha', sa.String(length=6), nullable=True, comment='Código do operador que gerou a senha, se aplicável'),
    sa.Column('cd_operador_cancelamento', sa.String(length=6), nullable=True, comment='Código do operador que cancelou o atendimento, se aplicável'),
    sa.Column('ds_observacao', sa.String(length=255), nullable=True, comment='Observações adicionais sobre o atendimento, se disponíveis'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano base do arquivo no formato YYYYMM (ex: 202401)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nome do arquivo de origem do atendimento'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data e hora de última atualização do registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_atendimentos_sao_lucas')),
    schema='slv',
    comment='Tabela de atendimentos importados da operadora São Lucas, na camada silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_atendimentos_sao_lucas', schema='slv')
    op.drop_table('tb_atendimentos_sao_lucas', schema='brz')
    # ### end Alembic commands ###
