"""make nr_request nullable in insurance_claims

Revision ID: dd26f3c77a69
Revises: ab09b1768619
Create Date: 2026-02-16 19:56:11.104936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd26f3c77a69'
down_revision: Union[str, Sequence[str], None] = 'ab09b1768619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurance_claims', 'nr_request',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_comment='Número da solicitação')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurance_claims', 'nr_request',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_comment='Número da solicitação')
    # ### end Alembic commands ###
