"""alter nm_file length to 255 in invoices

Revision ID: e49b739a5fec
Revises: 34c075198a77
Create Date: 2026-03-01 17:51:50.030565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49b739a5fec'
down_revision: Union[str, Sequence[str], None] = '34c075198a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'nm_file',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_comment='Nome do arquivo de origem',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'nm_file',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_comment='Nome do arquivo de origem',
               existing_nullable=False)
    # ### end Alembic commands ###
