"""add tb_solicitacoes_sao_lucas bronze

Revision ID: f7c4d50e21a4
Revises: a1b2c3d4e5f6
Create Date: 2026-03-07 19:50:37.926046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c4d50e21a4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_solicitacoes_sao_lucas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único do registro (UUID)'),
    sa.Column('solicitacao', sa.String(length=10), nullable=False, comment='Número da solicitação.'),
    sa.Column('data', sa.String(length=10), nullable=False, comment='Data da abertura da solicitação (formato: dd/mm/yyyy)'),
    sa.Column('validade_solicitacao', sa.String(length=10), nullable=False, comment='Data do vencimento da solicitação (formato: dd/mm/yyyy)'),
    sa.Column('solicitante', sa.String(length=5), nullable=False, comment='Código do profissinal de saúde solicitante'),
    sa.Column('operador', sa.String(length=255), nullable=False, comment='Código do usuário que registrou a solicitação no sistema'),
    sa.Column('terminal', sa.String(length=255), nullable=False, comment='Nome do usuário master do sistema para identificação de onde partiu a solicitação'),
    sa.Column('solicitante_1', sa.String(length=255), nullable=False, comment='Nome do profissional de saúde solicitante'),
    sa.Column('beneficiario', sa.String(length=18), nullable=False, comment='Código do beneficiário (código do paciente)'),
    sa.Column('beneficiario_1', sa.String(length=255), nullable=True, comment='Nome do beneficiário (nome do paciente)'),
    sa.Column('especialidade', sa.String(length=255), nullable=False, comment='Especialidade do profissional de saúde solicitante'),
    sa.Column('procedimento', sa.String(length=255), nullable=False, comment='Nome do procedimento solicitado'),
    sa.Column('qtde_sol', sa.String(length=3), nullable=False, comment='Quantidade do procedimento solicitado'),
    sa.Column('qtde_lib', sa.String(length=3), nullable=False, comment='Quantidade do procedimento solicitado que foi liberado pela operadora'),
    sa.Column('qtde_exe', sa.String(length=3), nullable=False, comment='Quantidade do procedimento solicitado que foi executado'),
    sa.Column('prestador', sa.String(length=255), nullable=True, comment='Código do prestador (código do profissional ou instituição que realizou o procedimento)'),
    sa.Column('especialidade_prestador', sa.String(length=255), nullable=True, comment='Especialidade do prestador que executou o procedimento solicitado'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Descrição do status da solicitação'),
    sa.Column('especificacao', sa.String(length=255), nullable=True, comment='Descrições de especificações e orientações relacionadas ao procedimento solicitado, se disponíveis'),
    sa.Column('tipo_de_solicitacao', sa.String(length=255), nullable=False, comment='Tipo de solicitação (ex: Consulta, Exame)'),
    sa.Column('operador_cancelamento', sa.String(length=255), nullable=True, comment='Código do operador que cancelou a solicitação, se aplicável'),
    sa.Column('observacao', sa.String(length=255), nullable=True, comment='Observações sobre a solicitação'),
    sa.Column('auditor', sa.String(length=255), nullable=True, comment='Código do usuário que realizou a auditoria da solicitação, se disponível'),
    sa.Column('data_agendamento', sa.String(length=10), nullable=True, comment='Data de agendamento para a realização do procedimento solicitado, se disponível (formato: dd/mm/yyyy)'),
    sa.Column('operador_agendamento', sa.String(length=255), nullable=True, comment='Código do operador que realizou o agendamento, se disponível'),
    sa.Column('dt_base', sa.Integer(), nullable=False, comment='Mês e ano base do arquivo no formato YYYYMM (ex: 202401)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nome do arquivo de origem do atendimento'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data e hora de última atualização do registro'),
    sa.Column('silver_exported', sa.Boolean(), nullable=False, comment='Flag indicando se o registro foi exportado para a camada silver'),
    sa.Column('silver_date_export', sa.DateTime(), nullable=True, comment='Data e hora de exportação para a camada silver'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_solicitacoes_sao_lucas')),
    schema='brz',
    comment='Tabela de solicitações importadas da operadora São Lucas, na camada bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_solicitacoes_sao_lucas', schema='brz')
    # ### end Alembic commands ###
